name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

permissions:
  contents: write # Needed for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: windows
            arch: amd64
            ext: .exe
          - os: darwin
            arch: amd64
            ext: ""
          - os: darwin
            arch: arm64
            ext: ""
          - os: linux
            arch: amd64
            ext: ""
          - os: linux
            arch: arm64
            ext: ""

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          go build -v -ldflags="-X main.Version=${VERSION}" -o "clai${{ matrix.ext }}" ./cmd/clai
          tar -czf "clai-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" "clai${{ matrix.ext }}"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clai-${{ matrix.os }}-${{ matrix.arch }}
          path: clai-${{ matrix.os }}-${{ matrix.arch }}.tar.gz

  create-release:
    needs: build-and-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          gh release create "$tag_name" \
            --title "CLAI $tag_name" \
            --notes "Release $tag_name" \
            ./*/*.tar.gz
